import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/landingpage/header/Header";
import Sliders from "../components/landingpage/header/Slider";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Levis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="mx-10 mt-2">
        <Image
          src="/assets/VERA_Images/Mask group@3x-3.png"
          width={1440}
          height={350}
        />
      </div>
      <div className="w-11/12 ml-10">
        <Sliders />
      </div>
    </div>
  );
};

export default Home;
